### ISSUE TITLE
Support for mocking methods in yaml

### ISSUE THREAD

**Issue by tomchinery** [tomchinery/yaml-fixtures#2]
Should be able to mock methods on the built object by using  ```__``` before the attribute name. Stubbed method should return that value. 
```
example: 
  example-1: 
    name: Test
    __someMethod: Hello
```
